name: OCI Factory Workflows - Build kubectl Rock

on:
  push:
    branches:
      - main

jobs:
  prepare-build:
    steps:
      - changed-files:
        uses: tj-actions/changed-files@531f5f7d163941f0c1c04e0ff4d8bb243ac4366f
        id: changed-files
        with:
          separator: ","
          dir_names: "true"
          files: |
            */rockcraft.y*ml
      - name: Validate image from dispatch
        id: validate-image
        run: |
          set -ex
          img_path="${{ steps.changed-files.outputs.all_changed_files }}"
          occurrences="${img_path//[^,]}"
          if [ ${#occurrences} -ne 0 ]
          then
            echo "ERR: can only build 1 image at a time, but trying to trigger ${img_path}"
            exit 1
          fi
          test -d "${img_path}"

          echo "img-version=$(echo "${img_path}" | cut -d '/' -f 1)" >> "$GITHUB_OUTPUT"
          echo "img-path=${img_path}" >> "$GITHUB_OUTPUT"


  build:
    needs: [prepare-build]
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "kubectl-rock"
      rock-repo: rockcrafters/kubectl-rock
      rock-repo-commit: main
      rockfile-directory: .
      arch-map: '{"amd64": ["ubuntu-latest"]}'

  publish:
    needs: [prepare-build, build]
    runs-on: ubuntu-latest
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/download-artifact@v4
        with:
          name: kubectl-rock

      - name: 'Set up skopeo'
        uses: warjiang/setup-skopeo@main
        with:
          version: latest

      - run: skopeo copy --multi-arch all oci-archive:kubectl-rock docker://ghcr.io/rockcrafters/kubectl-rock/kubectl:${{ steps.prepare-build.outputs.img-version }}
